### ISSUE TITLE
2021-03-20

### ISSUE THREAD

**Issue by xiaopeng163** [engeeker/python-for-kid-2021#2]
# About number

## 加减乘除

```
>>> a = 10
>>> b = 20
>>> 
>>> a + b
30
>>> a - b
-10
>>> a * b
200
>>> a / b
0.5
>>> 
>>> 
>>> (a + b) * 2
60
>>> c = a + b
>>> c
30
>>> d = (a + b) * 2
>>> d
60
>>> 
>>> 
>>> 2/2
1.0
>>> 4/2
2.0
>>> 120/2
60.0
>>> 
>>> 1/2
0.5
>>> 3/2
1.5
>>> 11/2
5.5
>>> 
```

## 奇数和偶数 odd and even
```
>>> 2 % 2      # 除2余数=0即为偶数
0
>>> 12222222222222222222%2
0
>>> 11212132132131313222221111111 % 2   # 除2余数=1即为奇数
1
>>> 11 % 4
3
>>> a
10
>>> b
20
>>> 
>>> 
>>> 
>>> 
```

## 比大小

```
>>> a = 10
>>> b = 20
>>> a > b    #  a不大于b，所以返回False假
False
>>> 
>>> a < b
True
>>> 
>>> (a + b) > b
True
>>> a
10
>>> b
20
>>> a = b
>>> a
20
>>> b
20
>>> a = 10
>>> a
10
>>> b
20
>>> 
>>> a == b    # a等于b吗？不等于，结果是假False
False
>>> 
>>> 
>>> c = 20
>>> b
20
>>> c
20
>>> b == c
True
>>> 
```

**Comment by xiaopeng163** [comment]
# about string


## 字符串的加法和乘法

```
>>> 
>>> 
>>> # string
>>> 
>>> color_1 = "red"
>>> color_2 = "blue"
>>> 
>>> 
>>> color_1
'red'
>>> 
>>> 
>>> color_2
'blue'
>>> 
>>> color_2 = 'black'
>>> 
>>> 
>>> color_2
'black'
>>> 
>>> 
>>> s1 = 'abc'
>>> s2 = 'xyz'
>>> 
>>> s1 + s2
'abcxyz'
>>> s1 - s2
Traceback (most recent call last):
  File "<pyshell#23>", line 1, in <module>
    s1 - s2
TypeError: unsupported operand type(s) for -: 'str' and 'str'
>>> s1 * s2
Traceback (most recent call last):
  File "<pyshell#24>", line 1, in <module>
    s1 * s2
TypeError: can't multiply sequence by non-int of type 'str'
>>> s1/s2
Traceback (most recent call last):
  File "<pyshell#25>", line 1, in <module>
    s1/s2
TypeError: unsupported operand type(s) for /: 'str' and 'str'
>>> s1
'abc'
>>> 
>>> counter = 3
>>> counter
3
>>> s1 * counter
'abcabcabc'
>>> 
>>> s1 * 3
'abcabcabc'
>>> s1* 3.1
Traceback (most recent call last):
  File "<pyshell#33>", line 1, in <module>
    s1* 3.1
TypeError: can't multiply sequence by non-int of type 'float'
>>> 
>>> 
```

## string index 字符串根据index访问元素

```
>>> s1
'abc'
>>> 
>>> 
>>> 
>>> # index
>>> 
>>> s2 = "abc12345xyz"
>>> s2
'abc12345xyz'
>>> 
>>> 
>>> 
>>> s3 = "abcabc"
>>> s3
'abcabc'
>>> 
>>> s3[1]
'b'
>>> s3[0]
'a'
>>> s3[1]
'b'
>>> s3[2]
'c'
>>> s3[3]
'a'
>>> s3[5]
'c'
>>> s3[1]
'b'
>>> 
>>> 
>>> 
>>> s4 = "abcde"
>>> s4
'abcde'
>>> 
>>> 
>>> 
>>> s4[0]
'a'
>>> s4[1]
'b'
>>> s4[2]
'c'
>>> s4[3]
'd'
>>> s4[4]
'e'
>>> 
>>> 
>>> 
>>> s5 = "123456"
>>> 
>>> s5
'123456'
>>> s5[3]
'4'
>>> s5[0]
'1'
>>> s5[1]
'2'
>>> s5[2]
'3'
>>> s5[3]
'4'
>>> s6 = '6789012'
>>> s6
'6789012'
>>> 
>>> 
>>> 
>>> 
>>> s6[4]
'0'
>>> s7 = 'jafljeofjeofiheaofiheofheohfeohfoeahfeohfe1212931293913912319239123192392jkekjfj'
>>> s7
'jafljeofjeofiheaofiheofheohfeohfoeahfeohfe1212931293913912319239123192392jkekjfj'
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> s5
'123456'
>>> # length = 6,  index=0,1,2,3,4,5
>>> len(s5)    # get the lenght 获取字符串长度
6
>>> len(s7)
80
>>> s7[79]
'j'
>>> 
```

**Comment by xiaopeng163** [comment]
# 

```
import turtle

p = turtle.Pen()

pen_color = "red"
fill_color = 'black'
length = 200
width = 100
angle = 90


p.forward(length)
p.right(angle)
p.forward(width)

```
